# Site settings
title: Web and Media Design Course · Amin Al Hazwani
description: Selvage distillery beard everyday carry, heirloom man braid freegan DIY asymmetrical kickstarter trust fund shoreditch pickled fanny pack.
url: "http://teaching.aminalhazwani.com" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown
future: bool
